version: '3.8'
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama_ultra_fast
    ports:
      - "11434:11434"
    volumes:
      - ollama_ultra_data:/root/.ollama
    environment:
      - OLLAMA_NUM_PARALLEL=1
      - OLLAMA_MAX_LOADED_MODELS=1
      - OLLAMA_FLASH_ATTENTION=1
      - OLLAMA_LOW_VRAM=true
      - OLLAMA_KEEP_ALIVE=2m
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2'
    restart: unless-stopped

volumes:
  ollama_ultra_data:
